PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS `event`;
CREATE TABLE `event` (
  -- `id` INTEGER AUTO_INCREMENT DEFAULT NULL,
  `reviews_count` INTEGER NULL DEFAULT NULL,
  `price` DECIMAL NULL DEFAULT NULL,
  `rating` DECIMAL NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `category` INTEGER NULL DEFAULT NULL,
  -- PRIMARY KEY (`id`),
  FOREIGN KEY (category) REFERENCES `category` (`id`)
);
DROP TABLE IF EXISTS `category`;
CREATE TABLE `category` (
  -- `id` INTEGER AUTO_INCREMENT DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL
  -- PRIMARY KEY (`id`)
);
COMMIT;
